### ISSUE TITLE
Capital City report display bug

### ISSUE THREAD

**Issue by KlaudiaJaros** [KlaudiaJaros/SEM-CW#72]
**Describe the bug**
Capital city reports print the country code instead of the country name. The header is also incorrect.

**To Reproduce**
1. Run the App.java
2. Find Capital City Reports
3. See the error: header is wrong - it says district instead of population
4. See the error: country name is not displayed, only country code

**Expected behavior**
Capital City reports should have the following columns: 
- Name.
- Country.
- Population. 

**Screenshots**
![bug](https://user-images.githubusercontent.com/56263298/115556013-16767700-a2a8-11eb-8953-cb42b7be5762.png)

**Desktop (please complete the following information):**
 - OS: Windows OS
 - IDE: IntelliJ 
 - Version: 0.1.0.3

**Comment by anathalie** [comment]
Capital city reports show country name instead of country code now, header has also been updated.
